identifier: m2638dzfh8h3o7zd
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: naatukodiblog
homeFolder: /Users/tirurao/Working/naatukodiblog
distFolder: ./dist/naatukodiblog
outDir: /Users/tirurao/Working/naatukodiblog/dist/static
handle404: ''
allowErrorCollect: true
