name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Chromium (for Puppeteer)
        run: sudo apt-get update && sudo apt-get install -y chromium-browser

      - name: Install Dependencies
        run: npm install
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true" # Use system-installed Chromium

      - name: Build Angular App
        run: npm run build

      - name: Generate Scully Static Pages
        run: npm run scully -- --serverTimeout=300000
        env:
          SCULLY_PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium-browser" # Use system-installed Chromium

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_SMOKE_00F32AC0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: "upload"
          app_location: "." # Root of the repository
          api_location: "" # API source code path (empty since you don't have an API)
          output_location: "dist/static" # Ensure Scully output directory is used

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_SMOKE_00F32AC0F }}
          action: "close"
